import Head from 'next/head';
import Footer from './Footer';
import HomePage from './Home';
import Navbar from './Navbar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <HomePage />
      <Footer />
    </div>
  );
}
